### ISSUE TITLE
Hash mismatch for ziglyph

### ISSUE THREAD

**Issue by amusingimpala75** [rockorager/libvaxis#1]
When trying to use `libvaxis` as a dependency, `zig` complains about a hash mismatch in `ziglyph`.
This also happened when I clone `libvaxis` and try to build it myself. I'm not sure what would have happened to result in this.

**Comment by rockorager** [comment]
What version of zig are you using? I am using `0.12.0-dev.2158+4f2009de1`, cleared my cache and did a fresh clone and it didn't complain at me.

**Comment by amusingimpala75** [comment]
0.11.0

**Comment by amusingimpala75** [comment]
let me try with zig master

**Comment by amusingimpala75** [comment]
Huh no that worked fine. Guess that's a bug with zig?

**Comment by rockorager** [comment]
I think there was a change in the hash method after `0.11.0`

**Comment by amusingimpala75** [comment]
Yeah I'll have to use `zig-nightly` I guess.
