### ISSUE TITLE
build failure on 0.14.0-dev.2448+d48611ba6 due to change in posix.sigaction function signature. 

### ISSUE THREAD

**Issue by mkrishnam18** [rockorager/libvaxis#123]
Compiling the example code from README.md with zig 0.14.0-dev.2448+d48611ba6 fails with 

`error: expected error union type, found 'void'
        try posix.sigaction(posix.SIG.WINCH, &act, null);
            ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~`

**Comment by rockorager** [comment]
This is expected. `main` will only build with zig 0.13.0. Once 0.14.0 is release, I will update `main`.

I have a [branch](https://github.com/rockorager/libvaxis/tree/zig-0.14.0) that *might* work - it works for `0.14.0-dev.2059+cdd8e82f0`, which is a bit behind the version you are trying.

**Comment by rockorager** [comment]
I just confirmed this works on the latest zig nightly (`0.14.0-dev.2456+a68119f8f`)
