### ISSUE TITLE
Emoji and decrqm_unicode

### ISSUE THREAD

**Issue by gwenn** [rockorager/libvaxis#127]
Hi,
I am trying to solve emoji rendering for [rustyline](https://github.com/kkawakam/rustyline/issues/826).
And `libvaxis` seems to use this sequence:
https://github.com/rockorager/libvaxis/blob/62854672ef2c7e70ff73056aa789db44efa69442/src/ctlseqs.zig#L9
to check how the current terminal behaves.
So I tried `zig build example -Dexample=cli`.
But some terminals don't behave correctly.
* alacritty => OK
![image](https://github.com/user-attachments/assets/57cd2305-5199-489e-9fbe-b126b9bceff1)
* iterm2 => KO
![image](https://github.com/user-attachments/assets/3667c4c2-29f5-4b4d-9f29-fe6089bb2b6e)
* kitty => KO
![image](https://github.com/user-attachments/assets/812fb7a4-33b0-49e0-8243-e3c505e600e1)
* Terminal.app => KO
![image](https://github.com/user-attachments/assets/e7673611-478f-4002-97e6-27de90c672fc)
* wezterm => OK
![image](https://github.com/user-attachments/assets/9c9896b4-0cdf-4203-9538-d07a654b2aae)

Those terminals answer to `decrqm_unicode` like:
* alacritty
```
[27, 91, 63, 50, 48, 50, 55, 59, 48, 36, 121]
[decrpm] 2027 => Some("Mode not recognized"`
```
* iterm2
```
[27, 91, 63, 50, 48, 50, 55, 59, 52, 36, 121]
[decrpm] 2027 => Some("Permanently reset")
```
* kitty
```
[27, 91, 63, 50, 48, 50, 55, 59, 48, 36, 121]
[decrpm] 2027 => Some("Mode not recognized")
```
* Terminal.app
garbage (sequence not supported?)
* wezterm
```
[27, 91, 63, 50, 48, 50, 55, 59, 51, 36, 121]
[decrpm] 2027 => Some("Permanently set")
```

How to check that DECRQM is not supported (by Mac Terminal) ?
How to handle `kitty` and `iterm2` which seem to support grapheme clusters but don't report accordingly ?
Thanks.

**Comment by rockorager** [comment]
## Terminal.app

For Terminal.app, there isn't much you can do. I would instead encourage users to use another terminal unfortunately. I will link the best comment I've ever read from [notcurses](https://github.com/dankamongmen/notcurses/blob/3a3c75e65ac8342f10a0e16eb63ab642aaf52ef4/src/lib/termdesc.c#L1087-L1095). As the comment suggests, you can check for `TERM_PROGRAM=Apple_Terminal`

## Kitty

Kitty does clustering but doesn't know about ZWJs. The way to calculate widths here is to strip ZWJs and then calculate using standard clustering techniques. I detect kitty in my go library by issuing an `XTVERSION` query and checking for the presence of "kitty" within the returned string. Kovid has stated he does not want to support mode 2027 style unicode.

## iTerm2

I don't use macOS so I haven't tested clustering capabilities on mac. Possibly you could use the `XTVERSION` query as in kitty.
