### ISSUE TITLE
help ziglyph to zg

### ISSUE THREAD

**Issue by AS400JPLPC** [rockorager/libvaxis#16]
Bonjour, est-il possible de changer "ziglyph" avec "ZG" du même auteur, plus simple et plus petit, plus rapide, Merci

Hello, is it possible to change "ziglyph" with "ZG" from the same author, simpler and smaller, faster, Thank you

**Comment by rockorager** [comment]
> Hello, is it possible to change "ziglyph" with "ZG" from the same author, simpler and smaller, faster, Thank you

Definitely! I hadn't realized that dude rewrote with the Ghostty optimizations.
I will definitely switch it over in the coming days. I did a quick look at the
API and it's a little bit different so it'll take slightly more than a direct
swap out, but not too much.

Thanks for the heads up!

**Comment by AS400JPLPC** [comment]
Thank you, take your time, it's not urgent.

**Comment by rockorager** [comment]
I started working on this. There are some significant API changes that would be required that I'm not sure I want to make. For example, in `Key.matches`, we are using case data. The `zg` case API requires allocation, which either means we need to have each `Key` event carry a case data pointer, or pass the data in. Both of these are pretty annoying from an API use case.

Looking at the benchmarks, I'm thinking of using `ziglyph` for _most_ of the current use, but swapping out specifically some hotpath items (mostly `display_width` which is ~3x faster in `zg` and is a hotpath for `libvaxis`). This would make libvaxis applications have even larger binary sizes, but it shouldn't be significant.

Any thoughts on this approach?

**Comment by AS400JPLPC** [comment]
The Ziglyph module will not keep up with the evolution of Zig. I'm telling you this because your work is important, you've put in effort, and as you say, the guy doesn't want to maintain the software anymore.
What I do in this specific case is I fork it and only take what I need.

I did that for zstring from the same author, because I only work in UTF8.

I'm nudging you a bit so that your work doesn't slowly become obsolete.

See you soon.

**Comment by rockorager** [comment]
> The Ziglyph module will not keep up with the evolution of Zig. I'm telling you
> this because your work is important, you've put in effort, and as you say, the
> guy doesn't want to maintain the software anymore. What I do in this specific
> case is I fork it and only take what I need.

I actually just noticed last night that ziglyph won't be maintained anymore, so
I will indeed be making the full switch. I will probably end up allocating the
data structures as globals to keep the API simple. I haven't thought about it
enough yet.

Thanks for the heads up, I appreciate it!

**Comment by rockorager** [comment]
Complete (mostly) in 8a71cd4. libvaxis now only uses `zg`
