### ISSUE TITLE
Key.matches doesn't work if num locks is enabled

### ISSUE THREAD

**Issue by Minemobs** [rockorager/libvaxis#19]
I was trying the TextInput example but I saw that the `Key.matches` function didn't work.
When checking if two keys matches, it checks if every modifiers are equals, including `.num_lock`.
Here's a video of the issue.

https://github.com/rockorager/libvaxis/assets/38861340/b1ee4210-10dd-4da9-a47d-037eda00eb90

**Comment by rockorager** [comment]
Thanks for reporting this! The fix also removes caps_lock for most cases.
