### ISSUE TITLE
API for text layout

### ISSUE THREAD

**Issue by rockorager** [rockorager/libvaxis#20]
Creating an issue to discuss API design around text layout. This came up on Discord, and has also been something I've been thinking about while building an IRC client.

## Problem

When printing distinct chunks of text, it is useful to know how much space the text will take up prior to printing. For example, when printing chat messages one might want to print bottom to top - requiring an application to know the height of a slice of segments prior to printing.

## Possible solutions
1. A function which returns how many lines a slice of Segments would take. This works ok but isn't very ergonomic.
2. A `View` widget which allows laying out text on an arbitrary sized screen (effectively printing it to a buffer), and then copying a Window from this screen to our actual Window
3. A line iterator over a slice of segments. The return value would have to be a struct which contains the segment and a bool to indicate if this segment is the first on a new line.

```zig
var iter = vaxis.LineIterator(&segments, width);
while (iter.next()) |seg| {
    if (seg.newline) {
        target_window.scroll(1);
    }
    // print to target window
}
```

I actually wonder if both options 2 and 3 should be implemented to cover broader use cases.

**Comment by rockorager** [comment]
As another option, I could make a function which accepts a width, slice of segments, and allocator. The function would layout all of the lines as a new slice of (allocated) structs containing a segment + bool for newline. This would be very flexible...you'd be able to iterate in reverse through lines, and also add up widths of a single line to allow justifying the text. Only downside is allocation - but might be worth it

**Comment by tomasz-lisowski** [comment]
Being able to query the post-render width and height of any renderable thing is exactly what I need in my app to be honest.

The simplest way to do this would be to perform a 'dry render' i.e. a render pass executing all the logic of the rendering algorithm but without writing to memory/screen. It would be accurate for any arbitrary shape, regardless of how complex it was to create. The obvious downside would be that you need to render things twice if you need their size but it would make it easy to, e.g., obtain the text size for any of the wrapping strategies without duplicating code.

I feel like to really know the best strategy performance-wise, we need some further testing. I suspect that depending on the situation, you might want the width/height using something similar to what I suggested, and at other times probably the `View` idea would be best, e.g., when rendering something very expensive like a fractal.

**Comment by rockorager** [comment]
> Being able to query the post-render width and height of any renderable thing
> is exactly what I need in my app to be honest.

What information would you need? Is this post window creation? We could make a
`layout` method that behaves exactly like `print` but doesn't write to the
underlying screen, and returns a struct that contains the final cursor position,
and whether or not there was more text to print (that last one is needed to know
if we ended on the final line and were done or ended on the final line and still
had more to print). This would only be helpful _post_ window creation, but
sounds like it might work for you?

> I feel like to really know the best strategy performance-wise, we need some
> further testing. I suspect that depending on the situation, you might want the
> width/height using something similar to what I suggested, and at other times
> probably the `View` idea would be best, e.g., when rendering something very
> expensive like a fractal.

Yeah, I think there will be use cases for both. Text processing is pretty fast,
and in fact my IRC client is essentially double rendering since I am calculating
the wrapped lines and _then_ rendering.

**Comment by rockorager** [comment]
Oh I can add this as an option the `PrintOptions` struct. And change the return
type to be the result.

```zig
const result = win.print(&segments, .{
    .commit = false,
});
```

Where the result is this struct:

```zig
pub const PrintResult = struct {
    col: usize,
    row: usize,
    overflow: bool,
};
```

**Comment by rockorager** [comment]
I am going to close this one for now. I think the current API returned from `print` works pretty decently. I am experimenting with a `skip_rows` print option as well, so you can feed in a slice of segments, and ignore the first `n` lines (still getting proper wrapping). This is helpful for say - printing a large amount of text but being partially scrolled down.
