### ISSUE TITLE
Zig build hangs

### ISSUE THREAD

**Issue by hedyhli** [rockorager/libvaxis#40]
Thanks for creating vaxis, I really enjoyed using the Go library!

I recently decided to try out Zig, so perhaps this issue comes from some misstep in my part.

Steps to reproduce
- `zig init`
- `zig fetch --save https://github.com/rockorager/libvaxis/archive/refs/tags/v0.2.0.tar.gz`
- `zig build`

It hangs at `Fetching packages 13/7`. If I SIGINT and run `zig build` again it hangs without any output.

Another way to reproduce
- Clone libvaxis
- `zig build`

Is there anything here I did incorrectly which might've caused this? I don't experience this issue with other dependencies I tried.

Or am I just being impatient? With git checked out at `v0.1.0` when I `zig build` it hangs for a while and finishes, so perhaps it's just that build time has increased after recent commits?

**Comment by hedyhli** [comment]
Update: build finished after 37 minutes, guess I was impatient 🤷

**Comment by rockorager** [comment]
> Update: build finished after 37 minutes, guess I was impatient 🤷 

Woah, that's a really long time - do you have a slow network / old hardware? zig build will fetch packages so slow internet could cause a long build...

**Comment by hedyhli** [comment]
Ah, I'm on M1 which should be pretty fast, so perhaps it's the network then.

On another note, is this how we're supposed to specify build options for vaxis as a dependency?

build.zig:
```zig
pub fn build(b: *std.Build) void {
    // ...
    const exe = b.addExecutable(.{
        // ...
    });

    const depVaxis = b.dependency("vaxis", .{
        // ...
        .libxev = false,
        .images = false,
        .nvim = false,
    });
    exe.root_module.addImport("vaxis", depVaxis.module("vaxis"));
    // ...
}
```

On build I get:
```
error: invalid option: -Dlibxev
error: invalid option: -Dnvim
error: invalid option: -Dimages
```

**Comment by rockorager** [comment]
>     const depVaxis = b.dependency("vaxis", .{
>         // ...
>         .libxev = false,
>         .images = false,
>         .nvim = false,
>     });

Yeah, that's exactly how you should define it. Are you also adding that on the
command line though? You only need to specify it in build.zig for passing
options to the module. Command line build options are only for your application.

**Comment by hedyhli** [comment]
Yep, with those lines in `build.zig` I then run `zig build`.

**Comment by hedyhli** [comment]
Hmm, I'm no longer having those errors after upgrading to 0.13.0. Sorry for the trouble.
