### ISSUE TITLE
Logs messing up with text_input example

### ISSUE THREAD

**Issue by glyh** [rockorager/libvaxis#67]
```
zig build -Dexample=text_input example
```

I got this:

![image](https://github.com/user-attachments/assets/012efc6c-474d-4edf-ab8d-7c5ae0101952)

Is this intended?

**Comment by rockorager** [comment]
This is intentional. The logs are written to stderr, so it's best to redirect stderr to a file or /dev/null.

I often forget to modify examples if I make breaking changes :)...overall libvaxis is quite stable now.

**Comment by rockorager** [comment]
When you build in ReleaseSafe or ReleaseFast these logs won't be present, FWIW.
