### ISSUE TITLE
No background colors in Dev TTY

### ISSUE THREAD

**Issue by LightSrc** [rockorager/libvaxis#74]
When you press Ctrl + Alt + F2 (In Linux) and you are in dev tty then run program some background colors are not visible.

For example
The Background Color for Selected Rows and Column Headers (Table)
Background for Cell Segment

These are just  I tested in my project, probably there is more.

**Comment by LightSrc** [comment]
Rgb

I am using this example
[https://github.com/rockorager/libvaxis/blob/main/examples/table.zig](https://github.com/rockorager/libvaxis/blob/main/examples/table.zig)

**Comment by rockorager** [comment]
Does setting `VAXIS_FORCE_LEGACY_SGR=1` fix it?

**Comment by LightSrc** [comment]
Nop

**Comment by rockorager** [comment]
What kernel version / distro do you have? I get a background color on the selected row as long as i have `VAXIS_FORCE_LEGACY_SGR=1` set. It seems like the linux console must be translating rgb codes to the 256 table - and some of the background colors merge into the same 256 color so you don't get the same fidelity.

**Comment by LightSrc** [comment]
I use Void linux distro with 6.6 kernel.
Does `VAXIS_FORCE_LEGACY_SGR=1` can be set as env variable on other PC (like it gets loaded in runtime) or it needs to be set when compiling project? I tried yet just setting that env variable in virtual machine.

**Comment by rockorager** [comment]
It should be set at runtime. `VAXIS_FORCE_LEGACY_SGR=1 zig build example -Dexample=table`, for example.

**Comment by LightSrc** [comment]
Yes, your command works on your example.

I tried for my project
```bash
export VAXIS_FORCE_LEGACY_SGR=1
zig build
./zig-out/bin/example
```

```bash
VAXIS_FORCE_LEGACY_SGR=1 zig build run
```

Both dont work, I am probably doing something wrong, will investigate it further.

**Comment by LightSrc** [comment]
I had too old libvaxis package specified in build.zig.zon which I took from libvaxis-starter repo. Now it works with env variable or just by setting in code ```vx.sgr = .legacy```

Thanks for helping me.
