### ISSUE TITLE
MacOS / VSCode Terminal - hex color is not right? Anyone else?

### ISSUE THREAD

**Issue by const-void** [rockorager/libvaxis#75]
Hello, very nice library. Love it!

OS: MacOS. vLatest
Zig: 0.13
Shell: zsh

**Terminal: VS Code**
Issue - in VS Code Terminal, I get a distorted true color
<img width="491" alt="macos-vscode-vxs-16m-color-test" src="https://github.com/user-attachments/assets/1c462b50-518a-46d6-b6e4-424779414bd3">

However when I do 'raw' ANSI via `echo` in the same VS Code terminal, true color appears to work.
<img width="372" alt="macos-vscode-zsh-16m-color-test" src="https://github.com/user-attachments/assets/baba6d5f-364f-4c79-a310-3c917e22484f">

**Work-around: kitty**
Running in kitty, color works perfectly!
<img width="718" alt="macos-kitty-vxs-16m-color-test" src="https://github.com/user-attachments/assets/a2d5503f-bee4-4caf-966b-b29141a70c37">

Wondering, what is our gut feel on where the issue is?  Does anyone else see it?  I  did all the VS Code tweaks (I think) for getting correct colors.

**Comment by rockorager** [comment]
Does it work if you set `VAXIS_FORCE_LEGACY_SGR=1`?

**Comment by rockorager** [comment]
For reference, vaxis will use ':' delimiters in SGR sequences unless it is told to do so otherwise. We automatically revert to ';' delimiters on windows, if we detect termux, or if we detect VHS.

At some point, I will add better detection for this :). For now, the environment variable can be used to force behavior (or if you are writing the app you can set `vaxis.sgr = .legacy` to always force it).

The "correct" behavior is to use ':' delimiters, which is why it is the default.

**Comment by const-void** [comment]
That fixed it! Thank you for the foresight to include the override.  I have always used ; delims so this I learn. 

> At some point, I will add better detection for this :). For now, the environment variable can be used to force behavior (or if you are writing the app you can set `vaxis.sgr = .legacy` to always force it).

Ah ok. I am not sure how one would detect tbh.  VS Code sets `"$TERM_PROGRAM" == "vscode"` ... so i suppose that could be a brute-forceish detector.

https://code.visualstudio.com/docs/terminal/shell-integration

thank you for the lib btw! It is very swank.

**Comment by rockorager** [comment]
> Ah ok. I am not sure how one would detect tbh.  VS Code sets `"$TERM_PROGRAM" == "vscode"` ... so i suppose that could be a brute-forceish detector.

I added this as a quirk in fa485c7. Thanks for the tip!
