### ISSUE TITLE
error: pts: /dev/pts/1 if create terminal after event loop

### ISSUE THREAD

**Issue by LightSrc** [rockorager/libvaxis#76]
I want dynamically initialize and deinitialize terminal (`vaxis.widgets.Terminal`), but I get `error: pts: /dev/pts/1` if I initialize after `loop.TryEvent` or `loop.NextEvent` basically after first frame. Is that a bug or I am supposed to initialize terminal in different way?

**Comment by rockorager** [comment]
On Wed Sep 4, 2024 at 7:14 PM CDT, LightSrc wrote:
> I want dynamically initialize and deinitialize terminal
> (`vaxis.widgets.Terminal`), but I get `error: pts: /dev/pts/1` if I initialize
> after `loop.TryEvent` or `loop.NextEvent` basically after first frame. Is that
> a bug or I am supposed to initialize terminal in different way?

It looks like that log happens no matter what. I'll change it to a debug log
since no actual error is occurring. Was the widget working, other than that?
