### ISSUE TITLE
Cursor Reset

### ISSUE THREAD

**Issue by karlseguin** [rockorager/libvaxis#77]
Thanks for the library.

This might just be something I'm doing wrong, but if I take the starter example and add:

```zig
win.setCursorShape(.beam_blink);
win.showCursor(1, 1);`
```

at the end of the `draw` method. When I exit the app (ctrl-c), the cursor shape doesn't get reset. From the documentation, I feel that the call to `self.vx.deinit()` should be good enough since it "Resets the terminal to it's original state".

**Comment by rockorager** [comment]
There is no way to get the state of the cursor shape from the terminal. *Some* terminals implement `\x1B[ q` to set the shape to the user configured default, but not all. I think a decent fallback would be to just reset it using that sequence, but this will still break for *some* people. The best way to handle this currently is for your shell to *always* set the cursor shape after the command has run (I believe fish already does this, for example).

**Comment by rockorager** [comment]
I realized my comment may not have made much sense.

There isn't a "real" way to set the cursor back to a the *default* cursor, and
there is no way to query the current cursor shape. If we could query, we'd do
that at startup and reset state on exit. Or we'd reset state to the default. But
neither of these are standard sequences. The options are:

1. Reset to `\x1b[ q`, which *some* terminals implement as "default", and though
   the spec says it's a blinking block.
2. Encourage users to have a post-cmd shell script to reset the cursor to their
   preferred option.
3. Write a new terminal spec for resetting cursor to default shape and/or
   querying the current shape.

Really, I think all of these need to be done with the current state of things.

**Comment by karlseguin** [comment]
Thanks for the answer, it helps
